[package]
name = "chatcmd"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
json = "0.12.4"
dotenv_codegen = "0.15.0"

[build-dependencies]
dotenv = "0.15.0"